### ISSUE TITLE
erreur "user unknow" après l'installation de alternc-mailman avec virtualmailman

### ISSUE THREAD

**Issue by sebas891** [AlternC/alternc-mailman#8]
Allo,
Après une installation fraiche sous wheezy de Alternc 3.2.10 et de Alternc-mailman 3.2 (avec la patch virtualmailman)  j'obtiens un bounce de postfix avec le message suivant:

`<pirulo-communautique.ca@communautique.ca>: user unknown
`

Sur le serveur, j'ai le message suivant:

`Mar 25 20:19:55 marvin postfix/pipe[1733]: 5154560025: to=<pirulo-communautique.ca@communautique.ca>, relay=mailman, delay=0.41, delays=0.25/0.02/0/0.15, dsn=5.1.1, status=bounced (user unknown)`

Je note le même bug sur une nouvelle installation en Debian Jessie avec les mêmes versions de logiciel d'alternc et de alternc-mailman.

Le code en cause semble ici:
https://github.com/AlternC/alternc-mailman/blob/3.2/bureau/class/m_mailman.php#L196

sinon, c'est un truc manquant dans la conf de postfix:
https://github.com/AlternC/AlternC/tree/master/etc/alternc/templates/postfix

Toutes les pistes de solution pour trouver la source ou des patchs seront appréciées!

Merci

**Comment by sebas891** [comment]
Question d'avoir la bonne version du code... dans le lien.

**Comment by sebas891** [comment]
voici la patch qui régle le problème sur la version alternc-mailman 3.2

```
diff --git a/m_mailman.php b/m_mailman.php
index 16c3009..734ec07 100644
--- a/m_mailman.php
+++ b/m_mailman.php
@@ -202,11 +202,11 @@ class m_mailman {
       return false;
     }
 
-    $recipient="$name$function";
-    $mail->add_wrapper($dom_id,$recipient,"mailman");
-
     if($this->is_vhost_applied){
-      $mail->create_alias($dom_id,"$login","$recipient@$domain","mailman");
+      $mail->add_wrapper($dom_id,"$login","mailman");
+    } else {
+      $recipient="$name$function";
+      $mail->add_wrapper($dom_id,$recipient,"mailman");
     }
 
     return true;    

```

**Comment by sebas891** [comment]
Je ne fermerai pas, question qu'un dev fasse un commit de ça.

Merci.

**Comment by camlafit** [comment]
Bonjour

Peux tu faire un PR plutôt :) ? ça sera plus rapide à intégrer.

Merci à toi

**Comment by sebas891** [comment]
Bon ici, j'ai pas revu le problème. On veut fermer ce bug à mon avis. On va voir avec le prochain release si ça se passe bien.
